<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NDI-MB-046" name="testRunners.TestRunner" tests="2" failures="1" timestamp="13 Apr 2019 06:55:42 GMT" time="7.234" errors="0">
  <testcase name="feature" time="5.038" classname="testRunners.TestRunner"/>
  <testcase name="feature" time="2.196" classname="testRunners.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at stepDefinations.CreateCustomerAPISteps.i_should_get_as_the_response_status_code(CreateCustomerAPISteps.java:142)
at âœ½.I should get 200 as the response status code(./src/test/resources/featureFiles/ValidateCreateCustomerAPI.feature:23)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- testRunners.TestRunner -->
